# Generated by Django 5.0.7 on 2024-07-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
